
var game_file_list = [
    //以下为自动修改，请勿修改
    //----auto game_file_list start----
	"libs/modules/egret/egret.js",
	"libs/modules/egret/egret.native.js",
	"libs/modules/eui/eui.js",
	"libs/modules/res/res.js",
	"libs/modules/socket/socket.js",
	"libs/modules/tween/tween.js",
	"libs/modules/game/game.js",
	"libs/modules/particle/particle.js",
	"libs/modules/md5/md5.js",
	"libs/cryptoJS/base64.js",
	"libs/cryptoJS/rc4.js",
	"bin-debug/framework/base/BaseUI.js",
	"bin-debug/framework/base/SingleClass.js",
	"bin-debug/gdmj/model/data/DeskInfo.js",
	"bin-debug/framework/base/BaseApp.js",
	"bin-debug/framework/base/BaseController.js",
	"bin-debug/framework/base/BasePanel.js",
	"bin-debug/framework/base/BaseScene.js",
	"bin-debug/framework/display/BitmapMovie.js",
	"bin-debug/gdmj/model/protocol/ProtocolData.js",
	"bin-debug/gdmj/view/game/lookrlue/LookRlue.js",
	"bin-debug/framework/net/CryptoUtils.js",
	"bin-debug/framework/net/HttpSender.js",
	"bin-debug/framework/net/SocketManager.js",
	"bin-debug/framework/utils/ArrayTool.js",
	"bin-debug/framework/utils/DateTimer.js",
	"bin-debug/framework/utils/DeviceUtils.js",
	"bin-debug/framework/utils/EffectUtils.js",
	"bin-debug/framework/utils/EventMananger.js",
	"bin-debug/framework/utils/Jsconfig.js",
	"bin-debug/framework/utils/LayerManager.js",
	"bin-debug/framework/utils/NumberTool.js",
	"bin-debug/framework/utils/ObjectPool.js",
	"bin-debug/framework/utils/PanelManager.js",
	"bin-debug/framework/utils/PopUpManager.js",
	"bin-debug/framework/utils/ResUtils.js",
	"bin-debug/framework/utils/SceneManager.js",
	"bin-debug/framework/utils/SoundManager.js",
	"bin-debug/framework/utils/StageUtils.js",
	"bin-debug/framework/utils/StringTool.js",
	"bin-debug/framework/utils/Tips.js",
	"bin-debug/gdmj/App.js",
	"bin-debug/gdmj/constant/AssetConst.js",
	"bin-debug/gdmj/constant/EventConst.js",
	"bin-debug/gdmj/constant/PanelConst.js",
	"bin-debug/gdmj/constant/SceneConst.js",
	"bin-debug/gdmj/model/data/BagInfo.js",
	"bin-debug/gdmj/model/data/ColorInfo.js",
	"bin-debug/gdmj/model/data/DebugInfo.js",
	"bin-debug/framework/adapter/AssetAdapter.js",
	"bin-debug/gdmj/model/data/ErrorCode.js",
	"bin-debug/gdmj/model/data/GameInfo.js",
	"bin-debug/gdmj/model/data/GoldRoomInfo.js",
	"bin-debug/gdmj/model/data/MarqueeInfo.js",
	"bin-debug/gdmj/model/data/ReplayInfo.js",
	"bin-debug/gdmj/model/data/RoomInfo.js",
	"bin-debug/gdmj/model/data/ServerInfo.js",
	"bin-debug/gdmj/model/data/ShareInfo.js",
	"bin-debug/gdmj/model/data/ShopInfo.js",
	"bin-debug/gdmj/model/data/SignInfo.js",
	"bin-debug/gdmj/model/data/UserInfo.js",
	"bin-debug/gdmj/model/data/WelfareInfo.js",
	"bin-debug/gdmj/model/data/WxInfo.js",
	"bin-debug/gdmj/model/DataCenter.js",
	"bin-debug/framework/net/ClientSocket.js",
	"bin-debug/gdmj/model/protocol/ProtocolHead.js",
	"bin-debug/gdmj/model/protocol/ProtocolHttp.js",
	"bin-debug/gdmj/model/vo/UserVO.js",
	"bin-debug/gdmj/view/common/BottomMenuManager.js",
	"bin-debug/gdmj/view/common/BottomMenus.js",
	"bin-debug/gdmj/view/common/LoadingLock.js",
	"bin-debug/gdmj/view/common/MessageBox.js",
	"bin-debug/gdmj/view/common/MessageBoxManager.js",
	"bin-debug/gdmj/view/common/PanelBg.js",
	"bin-debug/gdmj/view/game/actface/ActFaceBoom.js",
	"bin-debug/gdmj/view/game/actface/ActFaceFanQie.js",
	"bin-debug/gdmj/view/game/actface/ActFaceFlower.js",
	"bin-debug/gdmj/view/game/actface/ActFaceKiss.js",
	"bin-debug/gdmj/view/game/actface/ActFaceStone.js",
	"bin-debug/gdmj/view/game/actface/ActFaceUI.js",
	"bin-debug/gdmj/view/game/actface/ActFaceZan.js",
	"bin-debug/gdmj/view/game/chat/ChatItem.js",
	"bin-debug/gdmj/view/game/chat/ChatPanel.js",
	"bin-debug/gdmj/view/game/chat/ChatRecord.js",
	"bin-debug/gdmj/view/game/chat/FaceFactory.js",
	"bin-debug/gdmj/view/game/chat/FaceItem.js",
	"bin-debug/gdmj/view/game/chat/FaceMovie.js",
	"bin-debug/gdmj/view/game/chat/KeyWord.js",
	"bin-debug/gdmj/view/game/fanType/FanTypeItem.js",
	"bin-debug/gdmj/view/game/GameController.js",
	"bin-debug/gdmj/view/game/gamePanel/GameBack.js",
	"bin-debug/gdmj/view/game/gamePanel/GameMall.js",
	"bin-debug/gdmj/view/game/gamePanel/GameSet.js",
	"bin-debug/gdmj/view/game/GameScene.js",
	"bin-debug/gdmj/view/game/invite/InviteItem1.js",
	"bin-debug/gdmj/view/game/invite/InviteItem2.js",
	"bin-debug/gdmj/view/game/invite/InvitePanel.js",
	"bin-debug/gdmj/view/game/logic/CardFactory.js",
	"bin-debug/gdmj/view/game/logic/CardLogic.js",
	"bin-debug/framework/adapter/ThemeAdapter.js",
	"bin-debug/gdmj/view/game/matchInfo/MatchInfoPanel.js",
	"bin-debug/gdmj/view/game/modifyrlue/ModifyRlue1.js",
	"bin-debug/gdmj/view/game/option/OptionMenu.js",
	"bin-debug/gdmj/view/game/replay/ReplayControl.js",
	"bin-debug/gdmj/view/game/replay/ReplayLogic.js",
	"bin-debug/gdmj/view/game/result/LiuJuEffect.js",
	"bin-debug/gdmj/view/game/result/LoseEffect.js",
	"bin-debug/gdmj/view/game/result/ResultPanel.js",
	"bin-debug/gdmj/view/game/result/WinEffect.js",
	"bin-debug/gdmj/view/game/share/SharePanel.js",
	"bin-debug/gdmj/view/game/ui/ActTipUI.js",
	"bin-debug/gdmj/view/game/ui/Card.js",
	"bin-debug/gdmj/view/game/ui/DiceAnim.js",
	"bin-debug/gdmj/view/game/ui/EatComboUI.js",
	"bin-debug/gdmj/view/game/ui/HeadUI.js",
	"bin-debug/gdmj/view/game/ui/OutFlagUI.js",
	"bin-debug/gdmj/view/game/ui/RuleUI.js",
	"bin-debug/gdmj/view/game/ui/SelectActBtn.js",
	"bin-debug/gdmj/view/game/ui/SelectActUI.js",
	"bin-debug/gdmj/view/game/ui/SwapCardUI.js",
	"bin-debug/gdmj/view/game/ui/SystemTimeUI.js",
	"bin-debug/gdmj/view/game/ui/ZhuangFlag.js",
	"bin-debug/gdmj/view/game/voice/VoiceUI.js",
	"bin-debug/gdmj/view/game/zhuama/ZhuaMaPanel.js",
	"bin-debug/gdmj/view/hall/about/AboutPanel.js",
	"bin-debug/gdmj/view/hall/backpack/BackpackPanel.js",
	"bin-debug/gdmj/view/hall/bag/BagItem.js",
	"bin-debug/gdmj/view/hall/bag/BagPanel.js",
	"bin-debug/gdmj/view/hall/command/Avater.js",
	"bin-debug/gdmj/view/hall/command/BottomMenu.js",
	"bin-debug/gdmj/view/hall/command/GoldRoomBtn.js",
	"bin-debug/gdmj/view/hall/command/HallOption.js",
	"bin-debug/gdmj/view/hall/command/ItemIcon.js",
	"bin-debug/gdmj/view/hall/command/MenuButton.js",
	"bin-debug/gdmj/view/hall/command/PageView.js",
	"bin-debug/gdmj/view/hall/command/QRCode.js",
	"bin-debug/gdmj/view/hall/command/RoomBtn.js",
	"bin-debug/gdmj/view/hall/email/EmailItem.js",
	"bin-debug/gdmj/view/hall/email/EmailPanel.js",
	"bin-debug/gdmj/view/hall/email/EmailTwoPanel.js",
	"bin-debug/gdmj/view/hall/exroom/ExcRoom.js",
	"bin-debug/gdmj/view/hall/exroom/MinKeyBorad.js",
	"bin-debug/gdmj/view/hall/feedback/NewFeedBackPanel.js",
	"bin-debug/gdmj/view/hall/friend/FriendItem.js",
	"bin-debug/gdmj/view/hall/friend/FriendPanel.js",
	"bin-debug/gdmj/view/hall/fuli/FuliPanel.js",
	"bin-debug/gdmj/view/hall/HallController.js",
	"bin-debug/gdmj/view/hall/HallScene.js",
	"bin-debug/gdmj/view/hall/jjj/JjjPanel.js",
	"bin-debug/gdmj/view/hall/joinRoom/JoinNumber.js",
	"bin-debug/gdmj/view/hall/joinRoom/JoinRoomPanel.js",
	"bin-debug/gdmj/view/hall/lucky/Align.js",
	"bin-debug/gdmj/view/hall/mall/MallPanel.js",
	"bin-debug/gdmj/view/hall/mall/PaymentMethod.js",
	"bin-debug/gdmj/view/hall/mall/PaymentPanel.js",
	"bin-debug/gdmj/view/hall/marquee/Marquee.js",
	"bin-debug/gdmj/view/hall/othergame/OtherGame.js",
	"bin-debug/gdmj/view/hall/panel/CreateRoomPanel.js",
	"bin-debug/gdmj/view/hall/panel/ExRoomOpenVipPanel.js",
	"bin-debug/gdmj/view/hall/panel/InputRoomNumPanel.js",
	"bin-debug/gdmj/view/hall/rank/RankItem.js",
	"bin-debug/gdmj/view/hall/rank/RankItem1.js",
	"bin-debug/gdmj/view/hall/rank/RankNewRuleDetail.js",
	"bin-debug/gdmj/view/hall/rank/RankPanel.js",
	"bin-debug/gdmj/view/hall/rank/RankPanel1.js",
	"bin-debug/gdmj/view/hall/rank/RankRuleDetail.js",
	"bin-debug/gdmj/view/hall/rule/RulePanel.js",
	"bin-debug/gdmj/view/hall/score/LookPswPanel.js",
	"bin-debug/gdmj/view/hall/score/ScoreDetailItem.js",
	"bin-debug/gdmj/view/hall/score/ScoreDetailItem1.js",
	"bin-debug/gdmj/view/hall/score/ScoreDetailPanel.js",
	"bin-debug/gdmj/view/hall/score/ScoreDetailPanel1.js",
	"bin-debug/gdmj/view/hall/score/ScoreItem.js",
	"bin-debug/gdmj/view/hall/score/ScoreItem1.js",
	"bin-debug/gdmj/view/hall/score/ScorePanel.js",
	"bin-debug/gdmj/view/hall/score/ScorePanel1.js",
	"bin-debug/gdmj/view/hall/score/ScoreSharePanel.js",
	"bin-debug/gdmj/view/hall/set/SetPanel.js",
	"bin-debug/gdmj/view/hall/share/ShareItem.js",
	"bin-debug/gdmj/view/hall/shop/ReNew.js",
	"bin-debug/gdmj/view/hall/shop/SceneItem.js",
	"bin-debug/gdmj/view/hall/shop/ShopItem.js",
	"bin-debug/gdmj/view/hall/sign/SignAward.js",
	"bin-debug/gdmj/view/hall/sign/SignInPanel.js",
	"bin-debug/gdmj/view/load/PreloadPanel.js",
	"bin-debug/gdmj/view/login/LoginController.js",
	"bin-debug/gdmj/view/login/LoginScene.js",
	"bin-debug/Main.js",
	//----auto game_file_list end----
];

var window = this;

egret_native.setSearchPaths([""]);

egret_native.requireFiles = function () {
    for (var key in game_file_list) {
        var src = game_file_list[key];
        require(src);
    }
};

egret_native.egretInit = function () {
    egret_native.requireFiles();
    egret.TextField.default_fontFamily = "/system/fonts/DroidSansFallback.ttf";
    //egret.dom为空实现
    egret.dom = {};
    egret.dom.drawAsCanvas = function () {
    };
};

egret_native.egretStart = function () {
    var option = {
        //以下为自动修改，请勿修改
        //----auto option start----
		entryClassName: "Main",
		frameRate: 30,
		scaleMode: "fixedWidth",
		contentWidth: 750,
		contentHeight: 1334,
		showPaintRect: false,
		showFPS: false,
		fpsStyles: "x:0,y:0,size:30,textColor:0x00c200,bgAlpha:0.9",
		showLog: false,
		logFilter: "",
		maxTouches: 2,
		textureScaleFactor: 1
		//----auto option end----
    };

    egret.native.NativePlayer.option = option;
    egret.runEgret();
    egret_native.Label.createLabel(egret.TextField.default_fontFamily, 20, "", 0);
    egret_native.EGTView.preSetOffScreenBufferEnable(true);
};