
var game_file_list = [
    //以下为自动修改，请勿修改
    //----auto game_file_list start----
	"libs/modules/egret/egret.js",
	"libs/modules/egret/egret.native.js",
	"libs/modules/eui/eui.js",
	"libs/modules/res/res.js",
	"libs/modules/game/game.js",
	"libs/modules/tween/tween.js",
	"libs/modules/game/game.js",
	"libs/modules/socket/socket.js",
	"modules/md5/bin/md5/md5.js",
	"modules/cryptoJS/bin/cryptoJS/cryptoJS.js",
	"modules/JSLINQ/bin/JSLINQ/JSLINQ.js",
	"modules/physics/bin/physics/physics.js",
	"libs/modules/dragonBones/dragonBones.js",
	"modules/particle/bin/particle/particle.js",
	"modules/mouse/bin/mouse/mouse.js",
	"polyfill/promise.js",
	"bin-debug/base/KFController.js",
	"bin-debug/base/KFPanel.js",
	"bin-debug/base/KFScene.js",
	"bin-debug/base/SingleClass.js",
	"bin-debug/common/GlobalClass.js",
	"bin-debug/panel/bsfb/TaskPanel.js",
	"bin-debug/base/KFControllerMgr.js",
	"bin-debug/base/KFSceneManager.js",
	"bin-debug/AssetAdapter.js",
	"bin-debug/base/SoundMgr.js",
	"bin-debug/common/CommonFuc.js",
	"bin-debug/common/GameStartLogic.js",
	"bin-debug/base/KFPanelManager.js",
	"bin-debug/common/IMSdk.js",
	"bin-debug/common/LocalizationMgr.js",
	"bin-debug/common/ShadeFont.js",
	"bin-debug/common/StatisticalAnalysis.js",
	"bin-debug/controller/bsfb/BSFBExitPanelController.js",
	"bin-debug/controller/bsfb/BSFBExitSurePanelController.js",
	"bin-debug/controller/bsfb/GameHelpPanelController.js",
	"bin-debug/controller/bsfb/GamePanelController.js",
	"bin-debug/controller/bsfb/GameRankPanelController.js",
	"bin-debug/controller/bsfb/GameScorePanelController.js",
	"bin-debug/controller/bsfb/GameSettingPanelController.js",
	"bin-debug/controller/bsfb/LuckyPropsPanelController.js",
	"bin-debug/controller/bsfb/SlotHelpPanelController.js",
	"bin-debug/controller/bsfb/TaskPanelController.js",
	"bin-debug/controller/bsfb/TaskTipPanelController.js",
	"bin-debug/controller/bsfb/UploadVedioPanelController.js",
	"bin-debug/controller/bsfb/VedioPanelController.js",
	"bin-debug/controller/DemoPanelController.js",
	"bin-debug/controller/dice/CallDicePanelController.js",
	"bin-debug/controller/dice/DHTCreatRoomPanelController.js",
	"bin-debug/controller/dice/DHTGamePanelController.js",
	"bin-debug/controller/dice/DHTGuidPanelController.js",
	"bin-debug/controller/dice/DHTHelpPanelController.js",
	"bin-debug/controller/dice/DHTRoomListPanelController.js",
	"bin-debug/controller/dice/DHTSettingPanelController.js",
	"bin-debug/controller/dice/DiceGameController.js",
	"bin-debug/controller/dice/InviteFriendsPanelController.js",
	"bin-debug/controller/dice/InviteSettingPanelController.js",
	"bin-debug/controller/dice/InviteTitlePanelController.js",
	"bin-debug/controller/dice/JoinRoomPanelController.js",
	"bin-debug/controller/dice/PointSettingPanelController.js",
	"bin-debug/controller/dice/RoomLogPanelController.js",
	"bin-debug/controller/hall/AboutPanelController.js",
	"bin-debug/controller/hall/BindingPhonePanelController.js",
	"bin-debug/controller/hall/BindingTipPanelController.js",
	"bin-debug/controller/hall/ChangeNickNamePanelController.js",
	"bin-debug/controller/hall/GameProtectPanelController.js",
	"bin-debug/controller/hall/HallPanelController.js",
	"bin-debug/controller/hall/HallSettingPanelController.js",
	"bin-debug/controller/hall/MailPanelController.js",
	"bin-debug/controller/hall/MemberPanelController.js",
	"bin-debug/controller/hall/PersonalPanelController.js",
	"bin-debug/controller/hall/PhoneVerificationCodePanelController.js",
	"bin-debug/controller/hall/RollPanelController.js",
	"bin-debug/controller/hall/SecurityPanelController.js",
	"bin-debug/controller/hall/SharePanelController.js",
	"bin-debug/controller/hall/SystemTitlePanelController.js",
	"bin-debug/controller/login/AnonymousTipsPanelController.js",
	"bin-debug/controller/login/LoginChoicePanelController.js",
	"bin-debug/controller/login/StartPanelController.js",
	"bin-debug/controller/login/ThirdLoginPanelController.js",
	"bin-debug/controller/lztb/LZTBPanelController.js",
	"bin-debug/controller/share/AntiAddictionPanelController.js",
	"bin-debug/controller/share/BankPanelController.js",
	"bin-debug/controller/share/ChatPanelController.js",
	"bin-debug/controller/share/ClubDolePanelController.js",
	"bin-debug/controller/share/ClubPanelController.js",
	"bin-debug/controller/share/DialogPanelController.js",
	"bin-debug/controller/share/ExitPanelController.js",
	"bin-debug/controller/share/IDAuthenticatPanelController.js",
	"bin-debug/controller/share/PayChoicePanelController.js",
	"bin-debug/controller/share/PropshopPanelController.js",
	"bin-debug/controller/stone/StonePanelController.js",
	"bin-debug/controller/WXHH/WXHHPanelController.js",
	"bin-debug/controller/WXHH/WXHistoryPanellController.js",
	"bin-debug/controller/WXHH/WXMylogPanelController.js",
	"bin-debug/Main.js",
	"bin-debug/mode/Diamond.js",
	"bin-debug/net/MessageStruct.js",
	"bin-debug/net/MsgID.js",
	"bin-debug/net/NetEventMgr.js",
	"bin-debug/net/SendMsgForWebService.js",
	"bin-debug/net/ServerMsg.js",
	"bin-debug/net/ServiceWS.js",
	"bin-debug/net/WebSocketMgr.js",
	"bin-debug/panel/bsfb/BSFBExitPanel.js",
	"bin-debug/panel/bsfb/BSFBExitSurePanel.js",
	"bin-debug/panel/bsfb/GameHelpPanel.js",
	"bin-debug/panel/bsfb/GamePanel.js",
	"bin-debug/panel/bsfb/GameRankPanel.js",
	"bin-debug/panel/bsfb/GameScorePanel.js",
	"bin-debug/panel/bsfb/GameSettingPanel.js",
	"bin-debug/panel/bsfb/LuckyPropsPanel.js",
	"bin-debug/panel/bsfb/SlotHelpPanel.js",
	"bin-debug/base/AnimationMgr.js",
	"bin-debug/panel/bsfb/TaskTipPanel.js",
	"bin-debug/panel/bsfb/UI/BSHelpDropDownBOXUI.js",
	"bin-debug/panel/bsfb/UI/ExitSlider.js",
	"bin-debug/panel/bsfb/UI/GameRankItem.js",
	"bin-debug/panel/bsfb/UI/GameSlider.js",
	"bin-debug/panel/bsfb/UI/ScoreItem.js",
	"bin-debug/panel/bsfb/UI/VedioItem.js",
	"bin-debug/panel/bsfb/UploadVedioPanel.js",
	"bin-debug/panel/bsfb/VedioPanel.js",
	"bin-debug/panel/dice/CallDicePanel.js",
	"bin-debug/panel/dice/DHTCreatRoomPanel.js",
	"bin-debug/panel/dice/DHTGamePanel.js",
	"bin-debug/panel/dice/DHTGuidPanel.js",
	"bin-debug/panel/dice/DHTHelpPanel.js",
	"bin-debug/panel/dice/DHTRoomListPanel.js",
	"bin-debug/panel/dice/DHTSettingPanel.js",
	"bin-debug/panel/dice/InviteFriendsPanel.js",
	"bin-debug/panel/dice/InviteSettingPanel.js",
	"bin-debug/panel/dice/InviteTitlePanel.js",
	"bin-debug/panel/dice/JoinRoomPanel.js",
	"bin-debug/panel/dice/PointSettingPanel.js",
	"bin-debug/panel/dice/RoomLogPanel.js",
	"bin-debug/panel/hall/AboutPanel.js",
	"bin-debug/panel/hall/BindingPhonePanel.js",
	"bin-debug/panel/hall/BindingTipPanel.js",
	"bin-debug/panel/hall/ChangeNickNamePanel.js",
	"bin-debug/panel/hall/common/DropDownBoxUI.js",
	"bin-debug/panel/hall/common/LevelExpComponent.js",
	"bin-debug/panel/hall/common/MarqueenUI.js",
	"bin-debug/panel/hall/common/NewLevelExpComponent.js",
	"bin-debug/panel/hall/common/NoticeItems.js",
	"bin-debug/panel/hall/common/NoticeUI.js",
	"bin-debug/panel/hall/GameProtectPanel.js",
	"bin-debug/panel/hall/HallPanel.js",
	"bin-debug/panel/hall/HallSettingPanel.js",
	"bin-debug/panel/hall/MailPanel.js",
	"bin-debug/panel/hall/MemberPanel.js",
	"bin-debug/panel/hall/PersonalPanel.js",
	"bin-debug/panel/hall/PhoneVerificationCodePanel.js",
	"bin-debug/panel/hall/RollPanel.js",
	"bin-debug/panel/hall/SecurityPanel.js",
	"bin-debug/panel/hall/SharePanel.js",
	"bin-debug/panel/hall/SystemTitlePanel.js",
	"bin-debug/panel/load/LoadingUI.js",
	"bin-debug/panel/login/AnonymousTipsPanel.js",
	"bin-debug/panel/login/LoginChoicePanel.js",
	"bin-debug/panel/login/StartPanel.js",
	"bin-debug/panel/login/ThirdLoginPanel.js",
	"bin-debug/panel/lztb/LZTBPanel.js",
	"bin-debug/panel/PanelDemo.js",
	"bin-debug/panel/share/AntiAddictionPanel.js",
	"bin-debug/panel/share/BankPanel.js",
	"bin-debug/panel/share/ChatPanel.js",
	"bin-debug/panel/share/ClubDolePanel.js",
	"bin-debug/panel/share/ClubPanel.js",
	"bin-debug/panel/share/DialogPanel.js",
	"bin-debug/panel/share/ExitPanel.js",
	"bin-debug/panel/share/IDAuthenticatPanel.js",
	"bin-debug/panel/share/Item/ChatItem.js",
	"bin-debug/panel/share/Item/ClubDoleInfoItem.js",
	"bin-debug/panel/share/Item/ClubDoleLogItem.js",
	"bin-debug/panel/share/Item/ClubItem.js",
	"bin-debug/panel/share/Item/ClubJoinItem.js",
	"bin-debug/panel/share/Item/ClubJurisdictionItem.js",
	"bin-debug/panel/share/Item/ClubMemberItem.js",
	"bin-debug/panel/share/Item/ClubPositionItem.js",
	"bin-debug/panel/share/Item/ClubUpgradeItem.js",
	"bin-debug/panel/share/Item/ShopItem.js",
	"bin-debug/panel/share/PayChoicePanel.js",
	"bin-debug/panel/share/PropshopPanel.js",
	"bin-debug/panel/stone/Items/ArenaOneItem.js",
	"bin-debug/panel/stone/Items/ArenaTwoItem.js",
	"bin-debug/panel/stone/StonePanel.js",
	"bin-debug/panel/WXHH/Item/WXDropDownBOXUI.js",
	"bin-debug/panel/WXHH/Item/WXLogItem.js",
	"bin-debug/panel/WXHH/Item/WXRankAllItem.js",
	"bin-debug/panel/WXHH/Item/WXRankItem.js",
	"bin-debug/panel/WXHH/WXHHPanel.js",
	"bin-debug/panel/WXHH/WXHistoryPanel.js",
	"bin-debug/panel/WXHH/WXMylogPanel.js",
	"bin-debug/scene/AwakeScene.js",
	"bin-debug/scene/BSFBScene.js",
	"bin-debug/scene/DHSScene.js",
	"bin-debug/scene/HallScene.js",
	"bin-debug/scene/LoginScene.js",
	"bin-debug/scene/LZTBScene.js",
	"bin-debug/scene/STONEScene.js",
	"bin-debug/scene/WXHHScene.js",
	"bin-debug/ThemeAdapter.js",
	"bin-debug/util/base64-typescript-class.js",
	"bin-debug/util/DateTimer.js",
	"bin-debug/util/DeviceUtils.js",
	"bin-debug/util/LocalStorageUtil.js",
	"bin-debug/util/LogView.js",
	"bin-debug/util/ResUtils.js",
	"bin-debug/util/RgbUtil.js",
	//----auto game_file_list end----
];

var window = this;

egret_native.setSearchPaths([""]);

egret_native.requireFiles = function () {
    for (var key in game_file_list) {
        var src = game_file_list[key];
        require(src);
    }
};

egret_native.egretInit = function () {
    if(egret_native.featureEnable) {
        //控制一些优化方案是否开启
        var result = egret_native.featureEnable({
            
        });
    }
    egret_native.requireFiles();
    //egret.dom为空实现
    egret.dom = {};
    egret.dom.drawAsCanvas = function () {
    };
};

egret_native.egretStart = function () {
    var option = {
        //以下为自动修改，请勿修改
        //----auto option start----
		entryClassName: "Main",
		frameRate: 60,
		scaleMode: "noBorder",
		contentWidth: 900,
		contentHeight: 600,
		showPaintRect: false,
		showFPS: false,
		fpsStyles: "x:0,y:10,size:12,textColor:0xffffff,bgAlpha:0.9",
		showLog: false,
		logFilter: "",
		maxTouches: 2,
		textureScaleFactor: 1
		//----auto option end----
    };

    egret.native.NativePlayer.option = option;
    egret.runEgret();
    egret_native.Label.createLabel("/system/fonts/DroidSansFallback.ttf", 20, "", 0);
    egret_native.EGTView.preSetOffScreenBufferEnable(true);
};